### ISSUE TITLE
Remove duplicate location for organization name

### ISSUE THREAD

**Issue by timsutton** [mosen/ccp-recipes#15]
Currently the recipes in the `feature/ccpinfo` branch let you define the org name in two places, where a top-level `ORG_NAME` can override one specified in the `ccpinfo` dict, but I feel like this is an invitation for confusion and user error.

I'm testing some changes that would _only_ allow the user to specify it within `ccpinfo`, for the sake of consistency with where all other CCP-related settings are stored.

Would there be any opposition to them working this way?

I feel like being able to quickly override it would be convenient for people straddling multiple orgs, but that seems to me like it wouldn't be the common case. And even if people were needing to build multiple packages, it seems more cut and dry if each package contains its own overrides (which would at least result in different cache locations being used, possibly different names, etc.). I think organizationally it's clearer if it's a bit more work for someone to need to switch the orgs for different runs.

**Comment by mosen** [comment]
Yeah I've already seen one instance of confusion so we should stick to the ccpinfo dict
