### ISSUE TITLE
whats_my_org.sh failing - no organization name?

### ISSUE THREAD

**Issue by flammable** [mosen/ccp-recipes#17]
Hey Mosen!

Thanks for these recipes!  I'm having some trouble getting started, though.  When I run `whats_my_org.sh`, I get this output:

`Print: Entry, "0:orgName", Does Not Exist`

Is it possible we don't have an organization name?  How do I handle that in the recipe overrides?

Thanks!

Mike

**Comment by timsutton** [comment]
We've seen someone else with this issue before, and it seemed that their user wasn't actually associated as an admin with any org.

Are you Teams or Enterprise? If it's the latter, are you able to log into access the dashboard?

The actual team name is whatever is displayed in the upper-right-hand of the Enterprise Dashboard. The Teams admin interface also displays the org name somewhere as a heading or selection but I can't recall offhand where it is.

**Comment by flammable** [comment]
Thanks, Tim!  We have an Enterprise account.  When I go to login to the Adobe dashboard, I get "access denied" - so I guess I'm not an admin after all.  I'll see if I can get that changed.

Mike

**Comment by timsutton** [comment]
The simplest change you can probably request is to be given the Deployment Admin role. I've updated the README this morning in an attempt to better explain these requirements, since this issue definitely seems to be the most common initial stumbling block.

**Comment by flammable** [comment]
Thanks, Tim!  My manager tweaked the roles for our Adobe account, so whats_my_org.sh works now.

I appreciate the help and the documentation changes!

Mike
