### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by clburlison** [mosen/ccp-recipes#18]
I don't have time to create a PR ATM but I don't want to forget this. So below are the issues I ran into when trying to set this up from scratch today (let it be known I'm an AutoPkg moocher and do not have as much experience in this area)...

Points that need additional clarifying:
* product_id is now a different key sapCode (very confusing)
* I would go the next step and write out all of the three main overrides, `autopkg make-override -n PhotoshopCC2017.munki CreativeCloudApp.munki.recipe`, `autopkg make-override -n PhotoshopCC2017.jss CreativeCloudApp.jss.recipe`, `autopkg make-override -n PhotoshopCC2017.pkg CreativeCloudApp.pkg.recipe` (Clarifies a step that I overlooked)
* Should add a note on customerType needing to match. The output message clearly states this but it should be in the Readme as well. 

If I have time tomorrow I might be able to put together a generic setup tutorial and upload to YouTube. Start to finish with a sample build in ~5 minute video (speeding up the slow CCP parts). If I have time I'll give a link that can be used in this repo. Justify it as internal documentation.

Cheers

**Comment by timsutton** [comment]
Thanks for pointing these out. I'm now working through the 'creating the overrides' docs in an attempt to clear some of this up.

**Comment by timsutton** [comment]
I think the most recent updates I've added to the docs should clarify these things, so closing this.

**Comment by clburlison** [comment]
Awesome I think your changes cover mostly everything and help clarify the process. Two things left:

* `product_id` is still present under the "Input Variables" should be SAPCode
* under the "A base version:" sub heading the code block on the last line has a different tab character so GH renders it incorrectly.

**Comment by timsutton** [comment]
You're right - my changes didn't make it all the way down the document, so reopening.
