### ISSUE TITLE
Assumption of `AppLaunch` json key fails non-app recipes

### ISSUE THREAD

**Issue by timsutton** [mosen/ccp-recipes#25]
Since #21, the code in `CreativeCloudVersioner.py` which tries to build an `installs` key fails when it tries to read an `AppLaunch` key which is not present in all cases, i.e. Camera Raw.

IMO, for now we should just skip along and not do the installs array creation at all if we can't find this key, which would bring things back to the previous behaviour. I can think of several ways to address this but I don't think it's as high a priority as just wrapping these up and moving them to the autopkg org.

**Comment by jannheider** [comment]
This might be this error ?

```
The following recipes failed:
    AdobeCameraRawCC.munki.recipe
        Error in local.munki.CameraRawCC: Processor: CreativeCloudVersioner: Error: 'AppLaunch'
```

Is there a workaround ?

**Comment by timsutton** [comment]
For now the workaround will need to be the the Versioner code knows to skip doing `installs` item creation if there's no `AppLaunch` key. Not sure if perhaps someone else may get around to that before I do...

**Comment by timsutton** [comment]
This issue was moved to autopkg/adobe-ccp-recipes#5
