### ISSUE TITLE
hdiutil: create failed

### ISSUE THREAD

**Issue by jannheider** [mosen/ccp-recipes#26]
I updatet to the latest version of ccp-recipes (autopkg repo-update) and Creative Cloud Apps like Photoshop, Illustrator, Indesign are failing with:

```
 The following recipes failed:
     test-PhotoshopCC2017.munki
         Error in local.munki.test-PhotoshopCC2017: Processor: DmgCreator: Error: creation of /Users/Shared/xxx/Library/AutoPkg/Cache/local.munki.test-PhotoshopCC2017/CreativeCloudApp_Install-18.1.1.dmg failed: hdiutil: create failed - Es existiert keine Datei und kein Ordner dieser Art (Translation -> no file or folder found)
```

We also tried to make new overrides for the Munki recipes, same behavior. 

Going back to the Version we used before

`git reset --hard 68852d2`

Everything is working again.

Did we miss some changes that we have to do on our side ?

**Comment by timsutton** [comment]
You didn't miss any changes, it just appears that some work done in #21 has likely broken some things.

**Comment by timsutton** [comment]
Or.. possible in some of the later changes too.

**Comment by timsutton** [comment]
It's #23, which added `-%version%` to the built package name in `CreativeCloudApp.pkg.recipe`. I'm testing a fix for this now.

**Comment by timsutton** [comment]
@macmule I think it may be problematic for us to be putting the version in the actual `package_name` (as [here](https://github.com/mosen/ccp-recipes/blob/master/Adobe/CreativeCloudApp.pkg.recipe#L96-L97)). `makepkginfo` builds a `name` key like `AdobeApp-Version`, which will confuse Munki (and make a unique item per version).

Since this was originally added so that you get the version in the name of the zip, is there some other way this can be passed as an arg to JSSImporter?

**Comment by macmule** [comment]
Odd.. worked for me. (creation that is)

JSS recipes require a uniquely named .pkg.

Is there a file appender/renamer we could use for the .jss recipes?

**Comment by timsutton** [comment]
This seems to be rather hardcoded: https://github.com/sheagcraig/JSSImporter/blob/master/JSSImporter.py#L374-L379

**Comment by timsutton** [comment]
Creation worked for me until I deleted my cache, as well.

**Comment by timsutton** [comment]
But yeah, perhaps we could use FileMover for the JSS recipes so as to first rename the bundle pkg?

**Comment by macmule** [comment]
Ah.. [FileMover](https://github.com/autopkg/autopkg/wiki/Processor-FileMover).. that makes sense.

I'll be able to test later today/tonight.

If the package name changes are reverted in the meantime.. I can then try the FileMover for the jss recipes.

**Comment by timsutton** [comment]
I think the revert in c83afee8b2bdc4d93d3db199967ae4d97f6d270b should address this DmgCreator path issue with the .munki recipes.

**Comment by jannheider** [comment]
@timsutton 
Testet with Illustrator and it seems to work.

**Comment by timsutton** [comment]
Thanks for confirming!
