### ISSUE TITLE
Idea for supporting a custom check phase

### ISSUE THREAD

**Issue by timsutton** [mosen/ccp-recipes#4]
One thing that would be nice is if the recipes could still work using `--check`. One relatively simple approach would be to, after fetching the feed JSON, store the subset of it that applies only to the given product families (or at least just a list of available versions for a given set of SAPcodes). The fetch could then set `download_changed` to `True` if the fetched data is different from what has been already stored.

This would allow one to run the recipes using `--check` without needing to go through the full run of a recipe, which in the case of at least Munki recipes (and probably every other possible type as well) involves some kind of archiving process which is time-consuming on multi-GB files.

**Comment by mosen** [comment]
I'm not familiar enough with the mechanisms for `--check` but this sounds worthwhile so I'll take a look.

**Comment by mosen** [comment]
I've added the `download_changed` output as required but this also requires an EndOfCheckPhase i guess?

**Comment by timsutton** [comment]
Closing as this has been implemented for a while.
